% -------------------------------------------------------------------
%  Generated by MATLAB on 27-May-2019 22:47:51
%  MATLAB version: 9.6.0.1072779 (R2019a)
% -------------------------------------------------------------------
Ts = 0.002;
f1 = 100;
M = 1000;
x = [];
yn = [];
for n = 1:M
    x = [x cos(2*pi*(n-1)*Ts)+2*cos(2*pi*f1*(n-1)*Ts)];
    yn = [yn 2*cos(2*pi*f1*(n-1)*Ts)];
end
figure;
plot(x);
figure;
plot(yn);
[b0,a0] = butter(16,0.2);
y0 = filter(b0,a0,x);

[b1,a1] = butter(16,[0.2 0.6],'bandpass');
y1 = filter(b1,a1,x);
figure;
plot(y0);
figure;
plot(y1);
